/**
 * Profit KPI Template
 *
 * Defines the 18 profit and margin KPIs with display metadata.
 */

import type { AnalyticsTemplate } from '../../core/models';
import { registerTemplate } from '../../core';

export const profitKpiTemplate: AnalyticsTemplate = {
  key: 'profitKpis',
  name: 'KPIs de Lucros e Margens',
  description:
    'Calcula indicadores de lucro bruto, operacional, líquido, margens percentuais e rentabilidade combinando receitas e custos.',
  processor: 'profitKpis',
  requiredFields: [
    {
      key: 'revenueAmountField',
      label: 'Campo de Valor da Receita (Sales)',
      types: ['number'],
      description: 'Campo numérico que representa o valor da venda (receita).',
      required: true,
    },
    {
      key: 'revenueDateField',
      label: 'Campo de Data da Receita (Sales)',
      types: ['date'],
      description: 'Data usada para agrupar receitas por período.',
      required: true,
    },
  ],
  optionalFields: [
    {
      key: 'variableCostAmountField',
      label: 'Campo de Custo Variável (Expenses ou Movimentos)',
      types: ['number'],
      description: 'Campo numérico usado para custos variáveis na composição do lucro bruto.',
      required: false,
    },
    {
      key: 'fixedCostAmountField',
      label: 'Campo de Custo Fixo (Expenses)',
      types: ['number'],
      description: 'Campo numérico usado para custos fixos na composição de lucro operacional.',
      required: false,
    },
  ],
  defaultOptions: {
    type: 'bar',
    layout: 'kpiGrid',
    metricFormats: {
      'Lucro Bruto': 'currency',
      'Lucro Operacional': 'currency',
      'Lucro Líquido': 'currency',
      'Lucro Médio por Cliente': 'currency',
      'Lucro por Funcionário': 'currency',
      'Lucro por Hora Trabalhada': 'currency',
      'Margem Bruta (%)': 'percent',
      'Margem Operacional (%)': 'percent',
      'Margem Líquida (%)': 'percent',
      'Margem de Contribuição (%)': 'percent',
      'Rentabilidade Geral (%)': 'percent',
      'Crescimento do Lucro (%)': 'percent',
      'Produtividade do Lucro': 'number',
      'Eficiência do Lucro (Lucro/Custo)': 'number',
      'Índice de Qualidade do Lucro': 'percent',
      'Resultado Financeiro Final': 'currency',
      'Lucro Ajustado': 'currency',
      'Lucro Acumulado': 'currency',
    },
    metricDisplay: {
      'Lucro Bruto': 'graph',
      'Lucro Operacional': 'graph',
      'Lucro Líquido': 'card',
      'Lucro Médio por Cliente': 'card',
      'Lucro por Funcionário': 'graph',
      'Lucro por Hora Trabalhada': 'graph',
      'Margem Bruta (%)': 'gauge',
      'Margem Operacional (%)': 'gauge',
      'Margem Líquida (%)': 'gauge',
      'Margem de Contribuição (%)': 'gauge',
      'Rentabilidade Geral (%)': 'gauge',
      'Crescimento do Lucro (%)': 'graph',
      'Produtividade do Lucro': 'graph',
      'Eficiência do Lucro (Lucro/Custo)': 'card',
      'Índice de Qualidade do Lucro': 'gauge',
      'Resultado Financeiro Final': 'graph',
      'Lucro Ajustado': 'card',
      'Lucro Acumulado': 'graph',
    },
    metricChartTypes: {
      'Lucro Bruto': 'line',
      'Lucro Operacional': 'line',
      'Lucro Líquido': 'card',
      'Lucro Médio por Cliente': 'card',
      'Lucro por Funcionário': 'bar',
      'Lucro por Hora Trabalhada': 'line',
      'Margem Bruta (%)': 'gauge',
      'Margem Operacional (%)': 'gauge',
      'Margem Líquida (%)': 'gauge',
      'Margem de Contribuição (%)': 'gauge',
      'Rentabilidade Geral (%)': 'gauge',
      'Crescimento do Lucro (%)': 'line',
      'Produtividade do Lucro': 'line',
      'Eficiência do Lucro (Lucro/Custo)': 'card',
      'Índice de Qualidade do Lucro': 'gauge',
      'Resultado Financeiro Final': 'area',
      'Lucro Ajustado': 'card',
      'Lucro Acumulado': 'area',
    },
    metricAnalysis: {
      'Lucro Bruto': 'evolution',
      'Lucro Operacional': 'evolution',
      'Lucro Líquido': 'evolution',
      'Lucro Médio por Cliente': 'snapshot',
      'Lucro por Funcionário': 'comparison',
      'Lucro por Hora Trabalhada': 'comparison',
      'Margem Bruta (%)': 'evolution',
      'Margem Operacional (%)': 'evolution',
      'Margem Líquida (%)': 'evolution',
      'Margem de Contribuição (%)': 'evolution',
      'Rentabilidade Geral (%)': 'evolution',
      'Crescimento do Lucro (%)': 'evolution',
      'Produtividade do Lucro': 'comparison',
      'Eficiência do Lucro (Lucro/Custo)': 'comparison',
      'Índice de Qualidade do Lucro': 'composition',
      'Resultado Financeiro Final': 'evolution',
      'Lucro Ajustado': 'snapshot',
      'Lucro Acumulado': 'evolution',
    },
    metricHybrid: {
      'Margem Bruta (%)': true,
      'Margem Operacional (%)': true,
      'Margem Líquida (%)': true,
      'Margem de Contribuição (%)': true,
      'Rentabilidade Geral (%)': true,
    },
    metricDescriptions: {
      'Lucro Bruto': 'Receita menos custos variáveis diretos. Mede a lucratividade básica do negócio.',
      'Lucro Operacional': 'Lucro bruto menos custos fixos operacionais. Indica eficiência da operação.',
      'Lucro Líquido': 'Resultado final após todos os custos, impostos e despesas. O "bottom line".',
      'Lucro Médio por Cliente': 'Lucro médio gerado por cada cliente ativo no período. Avalia a rentabilidade da base.',
      'Lucro por Funcionário': 'Lucro dividido pelo número de colaboradores. Mede produtividade da equipe.',
      'Lucro por Hora Trabalhada': 'Lucro gerado por hora de trabalho. Indica retorno vs esforço.',
      'Margem Bruta (%)': 'Percentual do lucro bruto sobre a receita. Ideal: acima de 40% para serviços.',
      'Margem Operacional (%)': 'Percentual do lucro operacional sobre a receita. Mede eficiência operacional.',
      'Margem Líquida (%)': 'Percentual do lucro líquido sobre a receita. KPI mais importante de rentabilidade.',
      'Margem de Contribuição (%)': 'Quanto cada venda contribui para pagar custos fixos e gerar lucro.',
      'Rentabilidade Geral (%)': 'Retorno geral do negócio considerando todos os indicadores de rentabilidade.',
      'Crescimento do Lucro (%)': 'Variação do lucro entre períodos. Positivo indica crescimento saudável.',
      'Produtividade do Lucro': 'Índice de eficiência na geração de lucro em relação aos recursos utilizados.',
      'Eficiência do Lucro (Lucro/Custo)': 'Quanto de lucro é gerado para cada real investido em custos.',
      'Índice de Qualidade do Lucro': 'Mede a sustentabilidade do lucro — lucros recorrentes vs pontuais.',
      'Resultado Financeiro Final': 'Resultado consolidado do período considerando todas as receitas e despesas.',
      'Lucro Ajustado': 'Lucro após ajustes contábeis e não recorrentes. Visão mais precisa.',
      'Lucro Acumulado': 'Soma do lucro líquido ao longo do tempo. Mostra tendência de acumulação.',
    },
    metricIdealTargets: {
      'Margem Bruta (%)': 40,
      'Margem Operacional (%)': 20,
      'Margem Líquida (%)': 15,
      'Margem de Contribuição (%)': 35,
      'Rentabilidade Geral (%)': 20,
      'Crescimento do Lucro (%)': 10,
      'Índice de Qualidade do Lucro': 70,
    },
    metricHigherIsBetter: {
      'Lucro Bruto': true,
      'Lucro Operacional': true,
      'Lucro Líquido': true,
      'Lucro Médio por Cliente': true,
      'Lucro por Funcionário': true,
      'Lucro por Hora Trabalhada': true,
      'Margem Bruta (%)': true,
      'Margem Operacional (%)': true,
      'Margem Líquida (%)': true,
      'Margem de Contribuição (%)': true,
      'Rentabilidade Geral (%)': true,
      'Crescimento do Lucro (%)': true,
      'Produtividade do Lucro': true,
      'Eficiência do Lucro (Lucro/Custo)': true,
      'Índice de Qualidade do Lucro': true,
      'Resultado Financeiro Final': true,
      'Lucro Ajustado': true,
      'Lucro Acumulado': true,
    },
  },
  defaultParams: {
    period: 'month',
    monthsWindow: 12,
  },
};

registerTemplate(profitKpiTemplate);

