/**
 * Revenue KPI Template
 *
 * Defines the 17 revenue KPIs with display metadata.
 */

import type { AnalyticsTemplate } from '../../core/models';
import { registerTemplate } from '../../core';

export const revenueKpiTemplate: AnalyticsTemplate = {
  key: 'revenueKpis',
  name: 'KPIs de Receita',
  description:
    'Calcula indicadores-chave de receita (bruta, líquida, crescimento, ticket médio, concentração, novos e recorrentes).',
  processor: 'revenueKpis',
  requiredFields: [
    {
      key: 'amountField',
      label: 'Campo de Valor da Venda',
      types: ['number'],
      description: 'Campo numérico que representa o valor total da venda (receita bruta).',
      required: true,
    },
    {
      key: 'dateField',
      label: 'Campo de Data da Venda',
      types: ['date'],
      description: 'Campo de data usado para calcular períodos e janelas (ex.: mês).',
      required: true,
    },
  ],
  optionalFields: [
    {
      key: 'discountField',
      label: 'Campo de Desconto',
      types: ['number'],
      description: 'Campo numérico de descontos concedidos na venda.',
      required: false,
    },
    {
      key: 'taxField',
      label: 'Campo de Impostos',
      types: ['number'],
      description: 'Campo numérico de impostos incidentes na venda.',
      required: false,
    },
    {
      key: 'statusField',
      label: 'Campo de Status',
      types: ['select', 'string'],
      description: 'Campo de status da venda para exclusão de canceladas, estornos etc.',
      required: false,
    },
    {
      key: 'customerIdField',
      label: 'Campo de Cliente',
      types: ['string'],
      description: 'Identificador do cliente (usado para receita por cliente e recorrência).',
      required: false,
    },
    {
      key: 'categoryField',
      label: 'Campo de Categoria',
      types: ['string', 'select'],
      description: 'Categoria de venda/produto/serviço para cálculo de receita por categoria.',
      required: false,
    },
    {
      key: 'sourceField',
      label: 'Campo de Fonte de Receita',
      types: ['string'],
      description:
        'Fonte principal da receita (cliente, canal, filial, etc.). Se não informado, utiliza customerId ou categoria.',
      required: false,
    },
    {
      key: 'isNewCustomerField',
      label: 'Campo Cliente Novo (boolean)',
      types: ['boolean'],
      description:
        'Campo boolean indicando se a venda é de um cliente novo (usado para receita nova %).',
      required: false,
    },
    {
      key: 'isLoyalCustomerField',
      label: 'Campo Cliente Fiel (boolean)',
      types: ['boolean'],
      description:
        'Campo boolean indicando se o cliente é considerado fiel (usado para receita recorrente %).',
      required: false,
    },
  ],
  defaultOptions: {
    type: 'bar',
    layout: 'kpiGrid',
    metricFormats: {
      'Receita Bruta': 'currency',
      'Receita Líquida': 'currency',
      'Crescimento da Receita (%)': 'percent',
      'Receita Total Anual': 'currency',
      'Receita Operacional': 'currency',
      'Receita Não Operacional': 'currency',
      'Receita Média Mensal': 'currency',
      'Receita Média por Dia Útil': 'currency',
      'Receita por Hora Operacional': 'currency',
      'Receita por Cliente': 'currency',
      'Receita Máxima por Cliente': 'currency',
      'Receita por Categoria': 'currency',
      'Dependência de Receita de Fonte Única (%)': 'percent',
      'Receita Nova (%)': 'percent',
      'Receita Recorrente (%)': 'percent',
      'Receita Sazonal (Índice)': 'number',
      'Receita Atribuída a Campanhas': 'currency',
    },
    metricDisplay: {
      'Receita Bruta': 'graph',
      'Receita Líquida': 'graph',
      'Crescimento da Receita (%)': 'graph',
      'Receita Total Anual': 'graph',
      'Receita Operacional': 'graph',
      'Receita Não Operacional': 'graph',
      'Receita Média Mensal': 'graph',
      'Receita Média por Dia Útil': 'graph',
      'Receita por Hora Operacional': 'graph',
      'Receita por Cliente': 'graph',
      'Receita Máxima por Cliente': 'graph',
      'Receita por Categoria': 'graph',
      'Dependência de Receita de Fonte Única (%)': 'gauge',
      'Receita Nova (%)': 'gauge',
      'Receita Recorrente (%)': 'gauge',
      'Receita Sazonal (Índice)': 'graph',
      'Receita Atribuída a Campanhas': 'graph',
    },
    metricChartTypes: {
      'Receita Bruta': 'area',
      'Receita Líquida': 'line',
      'Crescimento da Receita (%)': 'bar',
      'Receita Total Anual': 'area',
      'Receita Operacional': 'donut',
      'Receita Não Operacional': 'donut',
      'Receita Média Mensal': 'line',
      'Receita Média por Dia Útil': 'line',
      'Receita por Hora Operacional': 'line',
      'Receita por Cliente': 'bar',
      'Receita Máxima por Cliente': 'bar',
      'Receita por Categoria': 'donut',
      'Dependência de Receita de Fonte Única (%)': 'gauge',
      'Receita Nova (%)': 'gauge',
      'Receita Recorrente (%)': 'gauge',
      'Receita Sazonal (Índice)': 'line',
      'Receita Atribuída a Campanhas': 'donut',
    },
    metricAnalysis: {
      'Receita Bruta': 'evolution',
      'Receita Líquida': 'evolution',
      'Crescimento da Receita (%)': 'evolution',
      'Receita Total Anual': 'snapshot',
      'Receita Operacional': 'composition',
      'Receita Não Operacional': 'composition',
      'Receita Média Mensal': 'snapshot',
      'Receita Média por Dia Útil': 'evolution',
      'Receita por Hora Operacional': 'evolution',
      'Receita por Cliente': 'comparison',
      'Receita Máxima por Cliente': 'comparison',
      'Receita por Categoria': 'composition',
      'Dependência de Receita de Fonte Única (%)': 'composition',
      'Receita Nova (%)': 'comparison',
      'Receita Recorrente (%)': 'comparison',
      'Receita Sazonal (Índice)': 'evolution',
      'Receita Atribuída a Campanhas': 'composition',
    },
    metricHybrid: {
      'Receita Total Anual': true,
      'Dependência de Receita de Fonte Única (%)': true,
      'Receita por Hora Operacional': true,
    },
    metricDescriptions: {
      'Receita Bruta': 'Soma total de todas as vendas antes de descontos e impostos. Indica o volume de negócios do período.',
      'Receita Líquida': 'Receita após descontos e impostos. Reflete o valor real que entra no caixa.',
      'Crescimento da Receita (%)': 'Variação percentual da receita entre o período atual e o anterior. Positivo indica crescimento.',
      'Receita Total Anual': 'Soma da receita nos últimos 12 meses (janela móvel). Visão anualizada do faturamento.',
      'Receita Operacional': 'Receita proveniente de atividades operacionais core do negócio.',
      'Receita Não Operacional': 'Receita de fontes secundárias ou não recorrentes, fora da operação principal.',
      'Receita Média Mensal': 'Faturamento médio por mês na janela de análise. Suaviza variações sazonais.',
      'Receita Média por Dia Útil': 'Receita dividida pelos dias úteis do mês. Mostra produtividade diária.',
      'Receita por Hora Operacional': 'Receita gerada por hora de trabalho (8h por dia útil). Mede eficiência horária.',
      'Receita por Cliente': 'Ticket médio geral — receita bruta dividida pelo número de clientes únicos.',
      'Receita Máxima por Cliente': 'Maior receita individual de um único cliente. Alta concentração pode ser risco.',
      'Receita por Categoria': 'Receita da maior categoria de produto/serviço. Identifica o segmento dominante.',
      'Dependência de Receita de Fonte Única (%)': 'Percentual da receita vindo da maior fonte individual. Acima de 30% é alerta de concentração.',
      'Receita Nova (%)': 'Parcela da receita vinda de clientes novos (primeira compra). Mede aquisição.',
      'Receita Recorrente (%)': 'Parcela da receita vinda de clientes fiéis (múltiplas compras). Mede retenção.',
      'Receita Sazonal (Índice)': 'Índice comparativo do período atual vs média. Acima de 100 indica período acima da média.',
      'Receita Atribuída a Campanhas': 'Receita total de vendas vinculadas a campanhas de marketing ativas.',
    },
    metricIdealTargets: {
      'Crescimento da Receita (%)': 15,
      'Dependência de Receita de Fonte Única (%)': 30,
      'Receita Nova (%)': 25,
      'Receita Recorrente (%)': 50,
    },
    metricHigherIsBetter: {
      'Crescimento da Receita (%)': true,
      'Dependência de Receita de Fonte Única (%)': false,
      'Receita Nova (%)': true,
      'Receita Recorrente (%)': true,
    },
  },
  defaultParams: {
    period: 'month',
    monthsWindow: 12,
    excludeStatuses: ['Cancelled'],
  },
};

registerTemplate(revenueKpiTemplate);

