import type { ITableSchema } from '../../../models/DynamicTable.model';
import { description, reportType } from '../../fields';

/**
 * @description Analytical Reports Module.
 */
export const reportsModule = {
  name: 'Reports',
  description: 'Stores analytical reports generated by the system.',
  category: 'operations',
  schema: {
    defaultDisplayField: 'type',
    fields: [
      reportType,
      { ...description, type: 'textarea', required: true },
    ],
  } as ITableSchema,
};
